package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Case 1")
    void generatedTest() {
        step("Open http://www.google.com", () -> {
            // todo
        });

        step("Search for Cookie Jar", () -> {
            // todo
        });

        step("First result should contains Cookie Jar", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'http://www.google.com'", () ->
            open("http://www.google.com"));

        step("Checking that the page title has is 'Google'", () -> {
            String expectedTitle = "Google";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}